-- Raw SQL
CREATE TABLE writings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  source_id INT, 
  title VARCHAR(255),
  body TEXT,
  page_num INT,
  created_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
